### ISSUE TITLE
please add custom selectable options like....

### ISSUE THREAD

**Issue by MrShortcut** [ilyub/vscode-autofold-comments#1]
hey i liked your version, please add custom selectable options,
like: - fold all regions eg.
make it editable in settings.json

"automaticFold": 'fold all regions'
either
"automaticFold": ['fold all regions', 'fold all block comments'] etc

**Comment by ilyub** [comment]
Hi. This is not planned. Feel free to fork.

**Comment by MrShortcut** [comment]
hahahah i hacked your version in local, but thanks
